server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/amigoscode
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  title: customer
  version: 1.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
