server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/amigoscode
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  title: fraud
  version: 1.0.0