spring:
  application:
    name: eureka-server

application:
  title: eureka-server
  version: 1.0.0

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
